name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "8.x"

    - name: Display dotnet version
      run: dotnet --version

    - name: Compile
      run: 	make

    - name: Zip rules directory
      run: |
        mkdir MxLintExtension
        cp bin/Debug/net8.0/* MxLintExtension
        zip -r extension.zip MxLintExtension

    - name: Get release
      id: get_release
      run: |
        echo "tag_name=v1.0.0" >> $GITHUB_OUTPUT
        echo "upload_url=test" >> $GITHUB_OUTPUT

      - name: Upload Release Asset (ZIP)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./extension.zip
          asset_name: MxLintExtension-${{ steps.get_release.outputs.tag_name}}.zip
          asset_content_type: application/zip


